# ECS field mappings — the lookup-table half of sigma_mapper.
#
# Kept in its own module so sigma_mapper.py stays scannable: the SigmaHQ
# dicts (majority of the line count) are pure lookup data copied from
# upstream and rarely change in step with the logic.

# ---------------------------------------------------------------------------
# SigmaHQ pySigma-backend-elasticsearch pipelines — source of truth
# ---------------------------------------------------------------------------
# The four dicts below are copied from the ECS pipelines in
# https://github.com/SigmaHQ/pySigma-backend-elasticsearch/tree/main/sigma/pipelines/elasticsearch.
# When SigmaHQ ships an update, mirror the change here rather than
# adding to ``RAW_TO_ECS_CUSTOM``.
#
# The ``.caseless`` suffix that SigmaHQ uses on lowercase-normalised
# multi-fields (``process.executable.caseless``) is preserved literally
# in these source-of-truth dicts and stripped when the runtime map is
# built — Sekoia's engine doesn't expose ``.caseless`` sub-fields.
#
# Fields with SigmaHQ context-aware mappings (Description, Product,
# Company, OriginalFileName, FileVersion, Signature, Initiated,
# Protocol, TargetObject) are intentionally omitted from the static
# dicts here and instead resolved via ``CONTEXT_AWARE_FIELDS`` below.

# From windows.py `ecs_windows()` — static field_mappings.
RAW_TO_ECS_SIGMAHQ_WINDOWS: dict[str, str] = {
    "AccountDomain": "user.domain",
    "AccountName": "user.name",
    "Application": "process.executable.caseless",
    "Archived": "sysmon.file.archived",
    "Channel": "winlog.channel",
    "ClientAddress": "source.ip",
    "ClientName": "source.domain",
    "CommandName": "powershell.command.name",
    "CommandPath": "powershell.command.path",
    "CommandType": "powershell.command.type",
    "ComputerName": "winlog.computer_name",
    "CurrentDirectory": "process.working_directory",
    "DestAddress": "destination.ip",
    "DestPort": "destination.port",
    "Destination": "process.executable.caseless",
    "DestinationHostname": "destination.domain",
    "DestinationIp": "destination.ip",
    "DestinationPort": "destination.port",
    "DestinationPortName": "network.protocol",
    "Device": "file.path",
    "EventID": "event.code",
    "FileName": "file.path",
    "HostApplication": "process.command_line",
    "HostId": "process.entity_id",
    "HostName": "process.title",
    "Image": "process.executable.caseless",
    "ImageLoaded": "file.path",
    "Imphash": "file.pe.imphash",
    "IpAddress": "source.ip",
    "IpPort": "source.port",
    "IsExecutable": "sysmon.file.is_executable",
    "MessageNumber": "powershell.sequence",
    "MessageTotal": "powershell.total",
    "NewEngineState": "powershell.engine.new_state",
    "NewProcessId": "process.pid",
    "NewProcessName": "process.executable.caseless",
    "NewProviderState": "powershell.provider.new_state",
    "ParentCommandLine": "process.parent.command_line",
    "ParentImage": "process.parent.executable.caseless",
    "ParentProcessGuid": "process.parent.entity_id",
    "ParentProcessId": "process.parent.pid",
    "ParentProcessName": "process.parent.name.caseless",
    "Payload": "powershell.file.script_block_text",
    "PipeName": "file.name",
    "PipelineId": "powershell.pipeline_id",
    "PreviousEngineState": "powershell.engine.previous_state",
    "ProcessGuid": "process.entity_id",
    "ProcessId": "process.pid",
    "ProcessName": "process.executable.caseless",
    "ProviderName": "powershell.provider.name",
    "Provider_Name": "winlog.provider_name",
    "QueryName": "dns.question.name",
    "QueryStatus": "sysmon.dns.status",
    "RunspaceId": "powershell.runspace_id",
    "ScriptBlockId": "powershell.file.script_block_id",
    "ScriptBlockText": "powershell.file.script_block_text",
    "ScriptName": "file.path",
    "SequenceNumber": "event.sequence",
    "SignatureStatus": "file.code_signature.status",
    "Signed": "file.code_signature.signed",
    "SourceAddress": "source.ip",
    "SourceHostname": "source.domain",
    "SourceImage": "process.executable.caseless",
    "SourceIp": "source.ip",
    "SourcePort": "source.port",
    "SourceProcessGuid": "process.entity_id",
    "SourceProcessId": "process.pid",
    "SourceThreadId": "process.thread.id",
    "TargetDomainName": "user.domain",
    "TargetFilename": "file.path",
    "User": "user.name",
    "WorkstationName": "source.domain",
    # TargetObject omitted here — see CONTEXT_AWARE_FIELDS.
}

# From macos.py `ecs_macos_esf()`.
RAW_TO_ECS_SIGMAHQ_MACOS: dict[str, str] = {
    "CommandLine": "process.command_line",
    "CurrentDirectory": "process.working_directory",
    "DestinationFilename": "file.target.path",
    "DestinationIp": "destination.ip",
    "DestinationPort": "destination.port",
    "EffectiveGroupId": "process.group.id",
    "EffectiveUserId": "process.user.id",
    "FileDirectory": "file.directory",
    "FileName": "file.name",
    "GroupId": "process.group.id",
    "Image": "process.executable.caseless",
    "KextIdentifier": "driver.name",
    "KextPath": "file.path",
    "MemoryProtection": "memory.protection",
    "ParentCommandLine": "process.parent.command_line",
    "ParentImage": "process.parent.executable.caseless",
    "ParentProcessId": "process.parent.pid",
    "ParentProcessName": "process.parent.name.caseless",
    "ProcessId": "process.pid",
    "ProcessName": "process.name.caseless",
    "PtraceRequest": "ptrace.request",
    "RealGroupId": "process.real_group.id",
    "RealUser": "process.real_user.name",
    "RealUserId": "process.real_user.id",
    "SignalNumber": "signal.number",
    "SignatureStatus": "process.code_signature.status",
    "Signed": "process.code_signature.exists",
    "SigningID": "process.code_signature.signing_id",
    "SourceFilename": "file.source.path",
    "SourceImage": "process.executable.caseless",
    "SourceIp": "source.ip",
    "SourcePort": "source.port",
    "SourceProcessId": "process.pid",
    "TargetFilename": "file.path",
    "TargetGroup": "group.target.name",
    "TargetGroupId": "group.target.id",
    "TargetImage": "target.process.executable.caseless",
    "TargetProcessGUID": "target.process.entity_id",
    "TargetProcessId": "target.process.pid",
    "TargetProcessName": "target.process.name.caseless",
    "TargetUser": "user.target.name",
    "TargetUserId": "user.target.id",
    "TeamID": "process.code_signature.team_id",
    "User": "process.user.name",
    "UserId": "process.user.id",
    "XpcServiceName": "xpc.service_name",
}

# From zeek.py `ecs_zeek_beats()`. Only literal, non-wildcard targets
# survive — SigmaHQ's `zeek.*.arg` wildcard patterns aren't usable as
# Sekoia ECS field names. List-of-target entries collapse to the last
# item (usually the most ECS-canonical).
RAW_TO_ECS_SIGMAHQ_ZEEK: dict[str, str] = {
    "AA": "zeek.dns.AA",
    "RA": "zeek.dns.RA",
    "RD": "zeek.dns.RD",
    "TC": "zeek.dns.TC",
    "TTLs": "dns.answers.ttl",
    "Z": "zeek.dns.Z",
    "action": "zeek.smb_files.action",
    "actions": "zeek.notice.actions",
    "addl": "zeek.weird.additional_info",
    "agent.version": "version",
    "agent_remote_id": "zeek.dhcp.agent_remote_id",
    "answer": "dns.answers.name",
    "answers": "dns.answers.name",
    "assigned_addr": "zeek.dhcp.assigned_addr",
    "auth_attempts": "zeek.ssh.auth.attempts",
    "auth_success": "zeek.ssh.auth.success",
    "auth_ticket": "zeek.kerberos.ticket.auth",
    "authentication_method": "zeek.rfb.auth.method",
    "basic_constraints.ca": "zeek.x509.certificate.basic_constraints.certificate_authority",
    "basic_constraints.path_len": "zeek.x509.certificate.basic_constraints.path_length",
    "bound_host": "zeek.socks.bound_host",
    "bound_name": "zeek.socks.bound_name",
    "bound_p": "zeek.socks.bound.port",
    "c-cookie": "http.cookie_vars",
    "c-ip": "source.ip",
    "c-uri": "url.original",
    "c-uri-extension": "url.extension",
    "c-uri-query": "url.query",
    "c-uri-stem": "url.original",
    "c-useragent": "user_agent.original",
    "cache_add_rx_ev": "zeek.connection.cache_add_rx_ev",
    "cache_add_rx_mpg": "zeek.connection.cache_add_rx_mpg",
    "cache_add_rx_new": "zeek.connection.cache_add_rx_new",
    "cache_add_tx_ev": "zeek.connection.cache_add_tx_ev",
    "cache_add_tx_mpg": "zeek.connection.cache_add_tx_mpg",
    "cache_del_mpg": "zeek.connection.cache_del_mpg",
    "cache_entries": "zeek.connection.cache_entries",
    "call_id": "zeek.sip.call_id",
    "cc": "zeek.smtp.cc",
    "cert_count": "zeek.rdp.cert.count",
    "cert_permanent": "zeek.rdp.cert.permanent",
    "cert_type": "zeek.rdp.cert.type",
    "certStatus": "zeek.ocsp.status",
    "certificate.cn": "zeek.x509.certificate.common_name",
    "certificate.curve": "zeek.x509.certificate.curve",
    "certificate.exponent": "zeek.x509.certificate.exponent",
    "certificate.key_alg": "zeek.x509.certificate.key.algorithm",
    "certificate.key_length": "zeek.x509.certificate.key.length",
    "certificate.key_type": "zeek.x509.certificate.key.type",
    "certificate.not_valid_after": "zeek.x509.certificate.valid.until",
    "certificate.not_valid_before": "zeek.x509.certificate.valid.from",
    "certificate.serial": "zeek.x509.certificate.serial",
    "certificate.sig_alg": "zeek.x509.certificate.signature_algorithm",
    "certificate.version": "zeek.x509.certificate.version",
    "cipher_alg": "zeek.ssh.algorithm.cipher",
    "circuit_id": "zeek.dhcp.circuit_id",
    "client_build": "zeek.rdp.client.build",
    "client_cert_subject": "zeek.kerberos.cert.client.subject",
    "client_dig_product_id": "zeek.rdp.client.product_id",
    "client_fqdn": "zeek.dhcp.client_fqdn",
    "client_header_names": "zeek.http.client_header_names",
    "client_issuer": "zeek.ssl.client_issuer",
    "client_major_version": "zeek.rfb.version.client.major",
    "client_message": "zeek.dhcp.client_message",
    "client_minor_version": "zeek.rfb.version.client.minor",
    "client_name": "zeek.rdp.client.name",
    "client_software": "zeek.dhcp.client_software",
    "client_subject": "zeek.ssl.client_subject",
    "clientIP": "source.ip",
    "clientip": "source.ip",
    "cmd": "zeek.mysql.cmd",
    "community": "zeek.snmp.community",
    "compile_ts": "zeek.pe.compile_time",
    "compression_alg": "zeek.ssh.algorithm.compression",
    "conn_state": "zeek.connection.conn_state",
    "conn_uids": "zeek.files.session_ids",
    "connect_info": "zeek.radius.connect_info",
    "content_type": "zeek.sip.content_type",
    "cookie": "zeek.rdp.cookie",
    "cookie_vars": "zeek.http.cookie_vars",
    "corelight_shunted": "zeek.connection.corelight_shunted",
    "cs-bytes": "http.request.body.bytes",
    "cs-cookie": "http.cookie_vars",
    "cs-host": "destination.domain",
    "cs-method": "http.request.method",
    "cs-referer": "http.request.referrer",
    "cs-version": "http.version",
    "cshka": "zeek.ssh.cshka",
    "curve": "zeek.ssl.curve",
    "cwd": "zeek.ftp.cwd",
    "cyu": "gquic.cyu",
    "cyutags": "gquic.cyutags",
    "data_channel.orig_h": "zeek.ftp.data_channel.originating_host",
    "data_channel.passive": "zeek.ftp.data_channel.passive",
    "data_channel.resp_h": "zeek.ftp.data_channel.response_host",
    "data_channel.resp_p": "zeek.ftp.data_channel.response_port",
    "dcc_file_name": "zeek.irc.dcc.file.name",
    "dcc_file_size": "zeek.irc.dcc.file.size",
    "dcc_mime_type": "zeek.irc.dcc.mime_type",
    "delta": "zeek.modbus.delta",
    "depth": "zeek.files.depth",
    "desktop_height": "zeek.rdp.desktop.height",
    "desktop_name": "zeek.rfb.desktop_name",
    "desktop_width": "zeek.rdp.desktop.width",
    "dest_domain": "server_name",
    "dest_ip": "destination.ip",
    "dest_port": "destination.port",
    "direction": "zeek.ssh.direction",
    "display_string": "zeek.snmp.display_string",
    "dns_addl": "zeek.dns.addl",
    "domain": "zeek.dhcp.domain",
    "domainname": "zeek.ntlm.domain",
    "dropped": "zeek.notice.dropped",
    "dst": "destination.ip",
    "dst_ip": "destination.ip",
    "dst_port": "destination.port",
    "duration": "event.duration",
    "email_body_sections": "zeek.notice.email_body_sections",
    "email_delay_tokens": "zeek.notice.email_delay_tokens",
    "encryption_level": "zeek.rdp.encryption.level",
    "encryption_method": "zeek.rdp.encryption.method",
    "endpoint": "zeek.dce_rpc.endpoint",
    "entropy": "zeek.files.entropy",
    "error_code": "zeek.kerberos.error.code",
    "error_msg": "zeek.kerberos.error.msg",
    "established": "zeek.ssl.established",
    "exception": "zeek.modbus.exception",
    "extracted": "zeek.files.extracted",
    "extracted_cutoff": "zeek.files.extracted_cutoff",
    "extracted_size": "zeek.files.extracted_size",
    "facility": "zeek.syslog.facility",
    "failure_reason": "dpd.failure_reason",
    "fc_reply": "dnp3.function.reply",
    "fc_request": "dnp3.function.request",
    "file_desc": "zeek.intel.file_desc",
    "file_mime_type": "zeek.intel.mime_type",
    "file_size": "zeek.ftp.file.size",
    "filename": "zeek.files.filename",
    "first_received": "zeek.smtp.first_received",
    "flash_version": "zeek.http.flash_version",
    "forwardable": "zeek.kerberos.forwardable",
    "framed_addr": "zeek.radius.framed_addr",
    "ftp_arg": "zeek.ftp.arg",
    "ftp_command": "zeek.irc.command",
    "func": "zeek.modbus.function",
    "get_bulk_requests": "zeek.snmp.get.bulk_requests",
    "get_requests": "zeek.snmp.get.requests",
    "gquic_user_agent": "zeek.gquic.user_agent",
    "gquic_version": "zeek.gquic.version",
    "hashAlgorithm": "zeek.ocsp.hash.algorithm",
    "hassh": "zeek.ssh.hassh",
    "hasshAlgorithms": "zeek.ssh.hasshAlgorithms",
    "hasshServer": "zeek.ssh.hasshServer",
    "hasshServerAlgorithms": "zeek.ssh.hasshServerAlgorithms",
    "hasshVersion": "zeek.ssh.hasshVersion",
    "has_cert_table": "zeek.pe.has_cert_table",
    "has_debug_data": "zeek.pe.has_debug_data",
    "has_export_table": "zeek.pe.has_export_table",
    "has_import_table": "zeek.pe.has_import_table",
    "height": "zeek.rfb.height",
    "helo": "zeek.smtp.helo",
    "history": "zeek.connection.history",
    "host": "zeek.intel.seen.host",
    "host_key": "zeek.ssh.host_key",
    "host_key_alg": "zeek.ssh.algorithm.host_key",
    "host_name": "zeek.dhcp.hostname",
    "hostname": "zeek.ntlm.hostname",
    "http_method": "http.request.method",
    "http_user_agent": "user_agent.original",
    "http_version": "http.version",
    "id.orig_h.name_src": "zeek.connection.id.orig_h_name.src",
    "id.orig_h.names_vals": "zeek.connection.id.orig_h_names.vals",
    "id.resp_h.name_src": "zeek.connection.id.resp_h_name.src",
    "id.resp_h.name_vals": "zeek.connection.id.resp_h_name.vals",
    "iin": "dnp3.inn",
    "in_reply_to": "zeek.smtp.in_reply_to",
    "indicator": "zeek.intel.seen.indicator",
    "indicator_type": "zeek.intel.seen.indicator_type",
    "info_code": "zeek.http.info_code",
    "info_msg": "zeek.http.info_msg",
    "irc_command": "zeek.ftp.command",
    "is_64bit": "zeek.pe.is_64bit",
    "is_exe": "zeek.pe.is_exe",
    "is_webmail": "zeek.smtp.is_webmail",
    "issuer": "zeek.ssl.issuer",
    "issuerKeyHash": "zeek.ocsp.hash.issuer.key",
    "issuerNameHash": "zeek.ocsp.hash.issuer.name",
    "ja3": "zeek.ssl.ja3",
    "ja3s": "zeek.ssl.ja3s",
    "kerberos_cipher": "zeek.kerberos.cipher",
    "kerberos_from": "zeek.smtp.from",
    "kerberos_service": "zeek.kerberos.service",
    "kex_alg": "zeek.ssh.algorithm.key_exchange",
    "keyboard_layout": "zeek.rdp.keyboard_layout",
    "last_alert": "zeek.ssl.last_alert",
    "last_reply": "zeek.smtp.last_reply",
    "lease_time": "zeek.dhcp.lease_time",
    "local_orig": "zeek.connection.local_orig",
    "local_resp": "zeek.connection.local_resp",
    "logcert": "zeek.x509.logcert",
    "mac": "zeek.radius.mac",
    "mac_alg": "zeek.ssh.algorithm.mac",
    "machine": "zeek.pe.machine",
    "mailfrom": "zeek.smtp.mail_from",
    "matched": "zeek.intel.matched",
    "md5": "zeek.files.md5",
    "message": "zeek.syslog.msg",
    "method": "http.request.method",
    "missed_bytes": "zeek.connection.missed_bytes",
    "missing_bytes": "zeek.files.missing_bytes",
    "mqtt_action": "smb.action",
    "msg": "zeek.notice.msg",
    "msg_id": "zeek.smtp.msg_id",
    "msg_orig": "zeek.dhcp.msg_orig",
    "msg_types": "zeek.dhcp.msg_types",
    "mysql_arg": "zeek.mysql.arg",
    "n": "zeek.notice.n",
    "name": "zeek.smb_files.name",
    "named_pipe": "zeek.dce_rpc.named_pipe",
    "native_file_system": "zeek.smb_mapping.native_file_system",
    "network_application": "network.protocol",
    "network_community_id": "network.community_id",
    "network_protocol": "network.transport",
    "new_ticket": "zeek.kerberos.ticket.new",
    "new_val": "zeek.modbus.new_val",
    "nextUpdate": "zeek.ocsp.update.next",
    "next_protocol": "zeek.ssl.next_protocol",
    "nick": "zeek.irc.nick",
    "node": "zeek.intel.seen.node",
    "notary": "zeek.ssl.notary",
    "note": "zeek.notice.note",
    "notice": "zeek.weird.notice",
    "ntp_version": "zeek.ntp.version",
    "ocsp_status": "zeek.ssl.oscp_status",
    "old_val": "zeek.modbus.old_val",
    "omniture": "zeek.http.omniture",
    "operation": "zeek.dce_rpc.operation",
    "orig_bytes": "source.bytes",
    "orig_cc": "source.geo.country_iso_code",
    "orig_certificate_sha1": "zeek.ssl.orig_certificate_sha1",
    "orig_filenames": "zeek.http.orig_filenames",
    "orig_ip_bytes": "zeek.connection.orig_ip_bytes",
    "orig_l2_addr": "source.mac",
    "orig_mime_types": "zeek.http.orig_mime_types",
    "orig_pkts": "source.packets",
    "origin": "zeek.http.origin",
    "overflow_bytes": "zeek.files.overflow_bytes",
    "p": "destination.port",
    "packet_segment": "dpd.packet_segment",
    "parent_domain": "dns.question.registered_domain",
    "passive": "zeek.ftp.passive",
    "peer": "zeek.weird.peer",
    "peer_descr": "zeek.notice.peer_descr",
    "peer_name": "zeek.notice.peer_name",
    "pop3_arg": "zeek.pop3.arg",
    "pop3_command": "zeek.pop3.command",
    "post_body": "zeek.http.post_body",
    "proto": "network.transport",
    "proxied": "zeek.http.proxied",
    "qclass": "zeek.dns.qclass",
    "qclass_name": "dns.question.class",
    "qtype": "zeek.dns.qtype",
    "qtype_name": "dns.question.type",
    "query": "dns.question.name",
    "question_length": "labels.dns.query_length",
    "r-dns": "destination.domain",
    "rcode": "zeek.dns.rcode",
    "rcode_name": "dns.response_code",
    "rcptto": "zeek.smtp.rcpt_to",
    "record_type": "dns.question.type",
    "referrer": "http.request.referrer",
    "register": "zeek.modbus.register",
    "rejected": "zeek.dns.rejected",
    "renewable": "zeek.kerberos.renewable",
    "reply_code": "zeek.ftp.reply.code",
    "request_body_len": "http.request.body.bytes",
    "request_from": "zeek.sip.request.from",
    "request_host": "zeek.socks.request_host",
    "request_name": "zeek.socks.request.host",
    "request_p": "zeek.socks.request.port",
    "request_path": "zeek.sip.request.path",
    "request_to": "zeek.sip.request.to",
    "request_type": "zeek.kerberos.request_type",
    "requested_addr": "zeek.dhcp.requested_addr",
    "requested_color_depth": "zeek.rdp.desktop.color_depth",
    "resp_bytes": "destination.bytes",
    "resp_cc": "destination.geo.country_iso_code",
    "resp_certificate_sha1": "zeek.ssl.resp_certificate_sha1",
    "resp_filenames": "zeek.http.resp_filenames",
    "resp_ip_bytes": "zeek.connection.resp.ip_bytes",
    "resp_l2_addr": "destination.mac",
    "resp_mime_types": "zeek.http.resp_mime_types",
    "resp_pkts": "destination.packets",
    "response": "zeek.mysql.response",
    "response_body_len": "http.response.body.bytes",
    "response_from": "zeek.sip.response.from",
    "response_path": "zeek.sip.response.path",
    "response_to": "zeek.sip.response.to",
    "result": "zeek.radius.result",
    "resumed": "zeek.ssl.resumed",
    "revokereason": "zeek.ocsp.revoke.reason",
    "revoketime": "zeek.ocsp.revoke.date",
    "rows": "zeek.mysql.rows",
    "rtt": "event.duration",
    "rx_hosts": "zeek.files.rx_host",
    "san.dns": "zeek.x509.san.dns",
    "san.email": "zeek.x509.san.email",
    "san.ip": "zeek.x509.san.ip",
    "san.uri": "zeek.x509.san.url",
    "sc-bytes": "http.response.body.bytes",
    "sc-status": "http.response.status_code",
    "second_received": "zeek.smtp.second_received",
    "section_names": "zeek.pe.section_names",
    "security_protocol": "zeek.rdp.security_protocol",
    "seen_bytes": "zeek.files.seen_bytes",
    "seq": "zeek.sip.seq",
    "serialNumber": "zeek.ocsp.serial_number",
    "server": "zeek.ssh.server",
    "server_addr": "destination.ip",
    "server_cert_subject": "zeek.kerberos.cert.server.subject",
    "server_dns_computer_name": "zeek.ntlm.server.name.dns",
    "server_major_version": "zeek.rfb.version.server.major",
    "server_message": "zeek.dhcp.server_message",
    "server_minor_version": "zeek.rfb.version.server.minor",
    "server_name": "zeek.ssl.server.name",
    "server_nb_computer_name": "zeek.ntlm.server.name.netbios",
    "server_software": "zeek.dhcp.server_software",
    "server_tree_name": "zeek.ntlm.server.name.tree",
    "set_requests": "zeek.snmp.set.requests",
    "severity": "zeek.syslog.severity",
    "sha1": "zeek.files.sha1",
    "sha256": "zeek.files.sha256",
    "share_flag": "zeek.rfb.share_flag",
    "share_type": "zeek.smb_mapping.share_type",
    "sip_method": "zeek.sip.sequence.method",
    "sip_subject": "zeek.sip.subject",
    "sip_user_agent": "zeek.sip.user_agent",
    "size": "zeek.smb_files.size",
    "smb_action": "smb.action",
    "smb_files_name": "zeek.smb_files.name",
    "smb_files_path": "zeek.smb_files.path",
    "smb_mapping_kerberos": "zeek.smb_mapping.service",
    "smb_mapping_path": "zeek.smb_mapping.path",
    "smtp_from": "zeek.kerberos.valid.from",
    "smtp_files_path": "zeek.smtp.path",
    "smtp_subject": "zeek.smtp.subject",
    "smtp_user_agent": "zeek.smtp.user_agent",
    "snmp_version": "zeek.snmp.version",
    "socks_version": "zeek.socks.version",
    "software_name": "zeek.software.name",
    "sources": "zeek.intel.seen.sources",
    "src": "source.ip",
    "src_ip": "source.ip",
    "src_port": "source.port",
    "ssh_version": "zeek.ssh.version",
    "ssl": "zeek.rdp.ssl",
    "ssl_cipher": "zeek.ssl.cipher",
    "ssl_subject": "zeek.ssl.subject",
    "status": "zeek.socks.status",
    "status_code": "http.response.status_code",
    "subject": "zeek.ssl.subject",
    "subpress_for": "zeek.notice.subpress_for",
    "subresource": "kubernetes.audit.objectRef.subresource",
    "subscriber_id": "zeek.dhcp.subscriber_id",
    "subsystem": "zeek.pe.subsystem",
    "success": "zeek.kerberos.success",
    "thisUpdate": "zeek.ocsp.update.this",
    "till": "zeek.kerberos.valid.until",
    "timedout": "zeek.files.timedout",
    "times_accessed": "zeek.smb_files.accessed",
    "times_changed": "zeek.smb_files.ctime",
    "times_created": "zeek.smb_files.created",
    "times_modified": "zeek.smb_files.mtime",
    "tls": "zeek.smtp.tls",
    "tls_cipher": "zeek.ssl.cipher",
    "tls_version": "zeek.ssl.version",
    "to": "zeek.smtp.to",
    "total_bytes": "zeek.files.total_bytes",
    "track_address": "zeek.modbus.track_address",
    "trans_id": "dns.id",
    "tunnel_action": "tunnel.action",
    "tunnel_client": "zeek.radius.tunnel_client",
    "tunnel_type": "zeek.tunnel.type",
    "ttl": "zeek.radius.ttl",
    "tx_hosts": "zeek.files.tx_host",
    "uid": "zeek.session_id",
    "up_since": "zeek.snmp.up_since",
    "uri": "url.original",
    "uri_vars": "zeek.http.uri_vars",
    "uses_aslr": "zeek.pe.uses_aslr",
    "uses_code_integrity": "zeek.pe.uses_code_integrity",
    "uses_dep": "zeek.pe.uses_dep",
    "uses_seh": "zeek.pe.uses_seh",
    "valid_ct_logs": "zeek.ssl.valid_ct_logs",
    "valid_ct_operators": "zeek.ssl.validct_operators",
    "valid_ct_operators_list": "zeek.ssl.valid_ct_operators_list",
    "validation_status": "zeek.ssl.validation_status",
    "value": "zeek.irc.command",
    "version_num": "zeek.ssl.version_num",
    "warning": "zeek.sip.warning",
    "weird_addl": "zeek.weird.additional_info",
    "weird_name": "zeek.weird.name",
    "where": "zeek.intel.seen.where",
    "width": "zeek.rfb.width",
    "x_originating_ip": "zeek.smtp.x_originating_ip",
}

# From kubernetes.py `ecs_kubernetes()`.
RAW_TO_ECS_SIGMAHQ_KUBERNETES: dict[str, str] = {
    "apiGroup": "kubernetes.audit.objectRef.apiGroup",
    "capabilities": "kubernetes.audit.requestObject.spec.containers.securityContext.capabilities.add",
    "hostPath": "kubernetes.audit.requestObject.spec.volumes.hostPath",
    "namespace": "kubernetes.audit.objectRef.namespace",
    "privileged": "kubernetes.audit.responseObject.spec.containers.securityContext.privileged",
    "resource": "kubernetes.audit.objectRef.resource",
    "subresource": "kubernetes.audit.objectRef.subresource",
    "username": "kubernetes.audit.user.username",
    "verb": "kubernetes.audit.verb",
}

# ---------------------------------------------------------------------------
# Custom mappings — fields SigmaHQ's pipelines don't cover
# ---------------------------------------------------------------------------
# These are ours (bespoke), covering cloud/audit taxonomies pySigma
# doesn't include. If SigmaHQ later adds any of these, delete from here
# to keep the SigmaHQ dicts as the single source of truth.
RAW_TO_ECS_CUSTOM: dict[str, str] = {
    # AWS CloudTrail
    "eventName": "event.action",
    "eventSource": "event.provider",
    "operationName": "event.action",
    "OperationName": "event.action",     # PascalCase variant seen in some rules
    "eventType": "event.action",         # CloudTrail eventType
    "EventType": "event.action",         # PascalCase variant
    "errorCode": "aws.cloudtrail.error_code",
    # ``requestParameters.*`` fields aren't mapped. Sekoia's aws-cloudtrail
    # parser stores the whole ``requestParameters`` object as a JSON blob
    # at ``aws.cloudtrail.flattened.request_parameters`` (verified against
    # SEKOIA-IO/intake-formats AWS/aws-cloudtrail/ingest/parser.yml) rather
    # than expanding subfields, so a flat ECS mapping would be symbolic.
    # A JSON-blob substring-match transform was considered but dropped —
    # only 4 rules in the ~3.6k Valhalla feed reference ``requestParameters.*``
    # (2 of which have shapes a transform could handle). Not worth the code
    # for the yield.
    # Azure activity + sign-in logs
    "properties.message": "azure.activitylogs.properties.message",
    "riskEventType": "azure.signinlogs.properties.risk_event_type",
    "AuthenticationRequirement": "azure.signinlogs.properties.authentication_requirement",
    "ResultType": "azure.signinlogs.properties.result_type",
    # Google Workspace admin/audit logs
    "auditType.action": "google_workspace.event.type",
    "auditType.category": "google_workspace.event.category",
    # Linux auditd — additional syscall args + core fields
    "SYSCALL": "auditd.data.syscall",
    "type": "auditd.log.record_type",
    "a0": "auditd.data.a0",
    "a1": "auditd.data.a1",
    "a2": "auditd.data.a2",
    "a3": "auditd.data.a3",
    "a4": "auditd.data.a4",
    "exe": "process.executable",
    "cfgpath": "auditd.data.cfgpath",
    # Windows Security event_data — Sekoia's Sysmon/Security parser
    # dumps unrecognised fields under `winlog.event_data.*`. SigmaHQ's
    # Windows pipeline auto-prefixes via a transformation; we enumerate
    # explicitly for predictability.
    "AccessList": "winlog.event_data.AccessList",
    "AccessMask": "winlog.event_data.AccessMask",
    "AttributeLDAPDisplayName": "winlog.event_data.AttributeLDAPDisplayName",
    "AttributeValue": "winlog.event_data.AttributeValue",
    "AuthenticationPackageName": "winlog.event_data.AuthenticationPackageName",
    "CallTrace": "winlog.event_data.CallTrace",
    "Category": "winlog.event_data.Category",
    "Configuration": "winlog.event_data.Configuration",
    "Contents": "winlog.event_data.Contents",
    "ContextInfo": "winlog.event_data.ContextInfo",
    "Data": "winlog.event_data.Data",
    "Details": "winlog.event_data.Details",
    "GrantedAccess": "winlog.event_data.GrantedAccess",
    "InterfaceUuid": "winlog.event_data.InterfaceUuid",
    "IsatapRouter": "winlog.event_data.IsatapRouter",
    "Level": "winlog.event_data.Level",
    "LogonType": "winlog.event_data.LogonType",
    "ModifyingApplication": "winlog.event_data.ModifyingApplication",
    "NewValue": "winlog.event_data.NewValue",
    "ObjectClass": "winlog.event_data.ObjectClass",
    "ObjectDN": "winlog.event_data.ObjectDN",
    "ObjectName": "winlog.event_data.ObjectName",
    "ObjectType": "winlog.event_data.ObjectType",
    "OpNum": "winlog.event_data.OpNum",
    "Path": "winlog.event_data.Path",
    "RelativeTargetName": "winlog.event_data.RelativeTargetName",
    "ShareName": "winlog.event_data.ShareName",
    "Status": "winlog.event_data.Status",
    "TaskName": "winlog.event_data.TaskName",
    # Users (Sigma canonical → ECS user.*)
    "SubjectUserName": "user.name",
    "TargetUserName": "user.target.name",
    # Windows event metadata variants
    "EventLog": "winlog.channel",
    # Sysmon fields not in SigmaHQ's static Windows map
    "IntegrityLevel": "process.integrity_level",
    "TargetImage": "process.executable",
    "ImagePath": "process.executable",
    "ServiceName": "service.name",
    "ServiceFileName": "service.executable",
    # Signature — SigmaHQ makes this context-aware
    # (driver_loaded / image_loaded only). Static fallback covers rules
    # in other contexts that still reference the field.
    "Signature": "file.code_signature.subject_name",
    # W3C ELF server-side URI fields. SigmaHQ Zeek covers only the
    # client-side variants (``c-uri``, ``c-uri-stem``); the ``cs-`` prefix
    # (server-log format) is common in IIS/proxy Sigma rules.
    "cs-uri": "url.original",
    "cs-uri-query": "url.query",
    "cs-uri-stem": "url.original",
    # W3C ELF variant (server-side ``userAgent`` camelCase — not
    # covered by Zeek, which uses ``http_user_agent``/``c-useragent``).
    "userAgent": "user_agent.original",
    # Kubernetes audit — dotted forms as they appear in Sigma rules.
    # SigmaHQ's pipeline maps the bare short names; some Sigma rules
    # use the fully-qualified `objectRef.*` path directly.
    "objectRef.resource": "kubernetes.audit.objectRef.resource",
    "objectRef.namespace": "kubernetes.audit.objectRef.namespace",
    "objectRef.name": "kubernetes.audit.objectRef.name",
    "objectRef.apiGroup": "kubernetes.audit.objectRef.apiGroup",
    "objectRef.subresource": "kubernetes.audit.objectRef.subresource",
    # Note: QueryName is intentionally NOT here — SigmaHQ Windows
    # already maps it (dns.question.name).
}


def _strip_caseless(target: str) -> str:
    """Sekoia's ECS schema doesn't advertise ``.caseless`` sub-fields;
    ship the base ECS target instead."""
    return target[:-9] if target.endswith(".caseless") else target


def _merge_sigmahq() -> dict[str, str]:
    """Build the runtime map with ``setdefault`` — the first pipeline to
    define a given source field wins. Order:

    1. SigmaHQ Windows — authoritative for shared field names since the
       Valhalla feed is majority Windows.
    2. Custom — bespoke overrides for fields Windows doesn't cover
       explicitly (e.g. ``TargetImage`` — pySigma macOS maps it to
       ``target.process.executable``, which is wrong for Windows rules).
    3. SigmaHQ macOS / Zeek / Kubernetes — fill the remaining gaps
       (macOS-, Zeek-, K8s-specific field names).

    ``.caseless`` targets are stripped since Sekoia's ECS schema doesn't
    expose those sub-fields.
    """
    merged: dict[str, str] = {}
    for pipeline in (
        RAW_TO_ECS_SIGMAHQ_WINDOWS,
        RAW_TO_ECS_CUSTOM,
        RAW_TO_ECS_SIGMAHQ_MACOS,
        RAW_TO_ECS_SIGMAHQ_ZEEK,
        RAW_TO_ECS_SIGMAHQ_KUBERNETES,
    ):
        for src, target in pipeline.items():
            merged.setdefault(src, _strip_caseless(target))
    return merged


# Runtime map used by the converter. Do not edit — edit the source dicts.
RAW_TO_ECS: dict[str, str] = _merge_sigmahq()


# ---------------------------------------------------------------------------
# Context-aware fields
# ---------------------------------------------------------------------------
# Fields whose ECS target depends on the Sigma rule's
# ``logsource.category``. Consulted BEFORE ``RAW_TO_ECS``. If the
# category isn't listed for a field, the rule is treated as unmapped
# (skipped) — matching SigmaHQ's conditional-mapping behaviour.
#
# The PE-metadata fields (Description, Product, Company, OriginalFileName,
# FileVersion) and Signature/Initiated/Protocol come from
# ``ecs_windows_variable_mappings`` in windows.py. TargetObject is our
# original bespoke context-aware branch (Sigma convention).
CONTEXT_AWARE_FIELDS: dict[str, dict[str, str]] = {
    # Bespoke — Sigma convention rather than pySigma.
    "TargetObject": {
        "registry_set": "registry.path",
        "registry_add": "registry.path",
        "registry_delete": "registry.path",
        "registry_rename": "registry.path",
        "registry_event": "registry.path",
        "file_event": "file.path",
    },
    # From SigmaHQ ecs_windows_variable_mappings:
    "FileVersion": {
        "process_creation": "process.pe.file_version",
        "image_load": "file.pe.file_version",
    },
    "Description": {
        "process_creation": "process.pe.description",
        "image_load": "file.pe.description",
        "sysmon_error": "winlog.event_data.Description",
    },
    "Product": {
        "process_creation": "process.pe.product",
        "image_load": "file.pe.product",
    },
    "Company": {
        "process_creation": "process.pe.company",
        "image_load": "file.pe.company",
    },
    "OriginalFileName": {
        "process_creation": "process.pe.original_file_name",
        "image_load": "file.pe.original_file_name",
    },
    "Protocol": {
        "network_connection": "network.transport",
    },
    "Initiated": {
        "network_connection": "network.direction",
    },
    # ``Signature`` is intentionally NOT here despite pySigma treating
    # it as context-aware — both categories (driver_loaded, image_loaded)
    # map to the same ECS target, so the static entry in
    # ``RAW_TO_ECS_CUSTOM`` covers all uses without gating on category.
}

# Fields produced by our own Stage 2 transforms (Hashes value split,
# context-aware rewrites) that are already ECS-shaped and must pass
# through the walker untouched. Also includes a handful of already-ECS
# field names some Sigma rules use directly (e.g. GCP audit fields).
_ECS_PASSTHROUGH_FIELDS: frozenset[str] = frozenset(
    {
        "process.hash.md5",
        "process.hash.sha1",
        "process.hash.sha256",
        "process.hash.sha512",
        "process.hash.imphash",
        "registry.path",
        "file.path",
        # GCP audit — Sigma rules already write these in ECS form.
        "gcp.audit.method_name",
        "gcp.audit.authentication_info.principal_email",
        "gcp.audit.authorization_info.permission",
        "gcp.audit.resource_name",
    }
)
